# Configuration de la base de données MySQL
db.driver=com.mysql.cj.jdbc.Driver
db.password=your_db_password_here
db.user=avnadmin
db.url=jdbc:mysql://hrflow-hrflow.f.aivencloud.com:21031/defaultdb?ssl-mode=REQUIRED&useSSL=true&requireSSL=true
